title: Claudia Avalos
logo: <img src="images/headshot.jpg" width="300" height="300"/>
#/assets/img/headshot_circle.png
#description: Aspiring Data Analyst
#show_dowloads: true
theme: jekyll-theme-minimal
